/** @format */

module.exports.users = [
  {
    id: "1",
    username: "sheldon",
    email: "test@gmail.com",
    passwd: "12345",
    country: "Canada",
    gridloc: "GN37os",
    priv: "user",
    units: "metric",
  },
  {
    id: "2",
    username: "carol",
    email: "carol@gmail.com",
    passwd: "abcde",
    country: "Canada",
    gridloc: "GN37os",
    priv: "user",
    units: "metric",
  },
  {
    id: "3",
    username: "molly",
    email: "molly@gmail.com",
    passwd: "abcde",
    country: "Canada",
    gridloc: "GN37os",
    priv: "user",
    units: "metric",
  },
  {
    username: "sheldon2",
    email: "stower@rogers.com",
    country: "can",
    gridloc: "gn",
    priv: "user",
    units: "metric",
    passwd: "12345",
    id: "4",
  },
  {
    username: "sheldon3",
    email: "stower1@rogers.com",
    country: "can",
    gridloc: "gn",
    priv: "user",
    units: "metric",
    passwd: "12345",
    id: "5",
  },
  {
    username: "sheldon4",
    email: "stower4@rogers.com",
    country: "can",
    gridloc: "gn",
    priv: "user",
    units: "metric",
    passwd: "12345",
    id: "6",
  },
];
