# fly.toml app configuration file generated for ham-locator-server-postgresql on 2024-05-05T09:29:51-02:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ham-locator-server-postgresql'
primary_region = 'yul'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
